package net.brusselsprout.sotw;

import net.brusselsprout.sotw.block.ModBlocks;
import net.brusselsprout.sotw.client.SOTWCreativeTab;
import net.brusselsprout.sotw.item.ModItems;
import net.brusselsprout.sotw.proxy.CommonProxy;
import net.brusselsprout.sotw.world.BiomeWarmJungle;
import net.minecraft.block.Block;
import net.minecraft.item.Item;
import net.minecraft.world.biome.Biome;
import net.minecraftforge.client.event.ModelRegistryEvent;
import net.minecraftforge.common.BiomeManager;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper;

@Mod(modid = SproutOTW.MODID, name = SproutOTW.NAME, version = SproutOTW.VERSION)
public class SproutOTW {

    public static final String MODID = "sotw";
    public static final String NAME = "Sprouts of the Wild";
    public static final String VERSION = "0.0.1";

    // TODO- right now, bananas are dropped from leaves. maybe add a actual block?
    // this would be implemented by a block on right click and check on neighbor changed if the leaf is removed.
    // can be generated by using the min foliage layer and radius of 1.

    @Mod.Instance
    public static SproutOTW instance;

    @SidedProxy(serverSide = "net.brusselsprout.sotw.proxy.CommonProxy", clientSide = "net.brusselsprout.sotw.proxy.ClientProxy")
    public static CommonProxy proxy;

    public static SimpleNetworkWrapper network;

    // Mod Feature Instances
    public static SOTWCreativeTab creativeTab = new SOTWCreativeTab();
    public static BiomeWarmJungle biomeWarmJungle = new BiomeWarmJungle();

    @Mod.EventHandler
    public void preInit(FMLPreInitializationEvent event) {
        proxy.registerRenderers();
    }

    @Mod.EventHandler
    public void init(FMLInitializationEvent event) {
        ModRecipes.init();
        BiomeManager.addBiome(BiomeManager.BiomeType.WARM, new BiomeManager.BiomeEntry(biomeWarmJungle, 2));
        BiomeManager.addSpawnBiome(biomeWarmJungle);
    }

    @Mod.EventHandler
    public void postInit(FMLPostInitializationEvent event) {

    }

    @Mod.EventBusSubscriber
    public static class RegistrationHandler {

        @SubscribeEvent
        public static void registerItems(RegistryEvent.Register<Item> event) {
            ModBlocks.registerItemBlocks(event.getRegistry());
            ModItems.register(event.getRegistry());
        }

        @SubscribeEvent
        public static void onEvent(final RegistryEvent.Register<Biome> event) {
            event.getRegistry().registerAll(
                    new BiomeWarmJungle().setRegistryName(SproutOTW.MODID, "warm_jungle")
            );
        }

        @SubscribeEvent
        public static void registerItems(ModelRegistryEvent event) {
            ModBlocks.registerModels();
            ModItems.registerModels();
        }

        @SubscribeEvent
        public static void registerBlocks(RegistryEvent.Register<Block> event) {
            ModBlocks.register(event.getRegistry());
        }
    }

}
